model_name: 'vgaraujov/t5-base-spanish'
target_langs: null
base_dir: '/home/julio/repos/queTrans/data/indi_langs_clean'
train_direction: 'both'
learning_rate: 2e-5
per_device_train_batch_size: 64
per_device_eval_batch_size: 64
num_train_epochs: 200
eval_steps: 100
output_dir: './assets/t5-base-spanish/biSpaNat_uniform'
early_stopping: True
early_stopping_patience: 5
uniform_sample: True 